# Generated by Django 3.2 on 2021-10-07 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Contuct',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HonerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='HonerProfilePicture')),
                ('name', models.CharField(max_length=30)),
                ('education', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=30)),
                ('contruct', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ToLetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tolet_category_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TopAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopaddImg', models.ImageField(upload_to='Topadd Picture')),
                ('title', models.TextField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Userpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='tolet.png', upload_to='picture')),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=14)),
                ('details', models.TextField()),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biggaponbdapp.category')),
                ('tolet_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biggaponbdapp.toletcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImg', models.ImageField(default='no_img.jpg', upload_to='profile_picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
